feat: add image exporter (#1)
feat: progress and speed metrics (#2)

- add progress with percent and a speed
- add ca-certificates package to work with https endpoints
- dedup in Taskfile

feat(image-exporter): inspect source image (#3)

Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>

fix: could not build cdi-registry-importer on MacOS (#4)

* fix: pkg/importer/vddk-datasource_arm64.go:47:39: undefined: io

Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>

* fix: could not build cdi-registry-importer on MacOS

Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>

---------

Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>

feat(registry-importer): add termination message

feat(registry-importer): add gz and xz formats support

feat(registry-importer): add iso and compressed iso formats support

feat(registry-importer): improve log messages, add tiny images support

feat(registry-importer): added comments

fix(registry-importer): fix registry importer pushing

Feature/ci (#8)

* fix(registry-importer): add gh workflow

* fix(registry-importer): use secrets.GITHUB_TOKEN instead github.token

* fix(registry-importer): new registry name

* fix(registry-importer): set token permissions clearly

* fix(registry-importer): set new username to login docker

* fix(registry-importer): use dev-registry.deckhouse.io instead of ghcr.io

* fix(registry-importer): fix env variable

* fix(registry-importer): fix env variable

* fix(registry-importer): fixed linter errors

* fix(registry-importer): added linter

* fix(registry-importer): fixed linter errors

* fix(registry-importer): run gh wf jobs sequentially

* feat(registry-importer): improved tasks

* Update .github/workflows/registry-importer.yaml

Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>

---------

Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>
Co-authored-by: Dmitry Rakitin <dmitry.rakitin@flant.com>
Co-authored-by: Aleksei Igrychev <aleksei.igrychev@palark.com>

Feat/uploader (#9)

* feat(registry-uploader): added uploadserver

* feat(registry-uploader): removed unnecessary consts

* feat(registry-uploader): fixed filename for upload data source

* feat(registry-uploader): fixed progress metrics

Migrating the DataSourceInterface (#3)

* Remove DataSourceInterface interface implementations.
* Add public aliases for useful private methods.

---------

Co-authored-by: Yaroslav Borbat <yaroslavborbat@Yaroslavs-MacBook-Air.local>

feat: cut importer and uploader binary sources

rm legacy

Signed-off-by: yaroslavborbat <yaroslav.752@gmail.com>

rm legacy

Signed-off-by: yaroslavborbat <yaroslav.752@gmail.com>